		<link href="../_/css/bootstrap-theme.css" rel="stylesheet">
		<link href="../_/css/bootstrap-theme.min.css" rel="stylesheet">
		<link href="../_/css/bootstrap.min.css" rel="stylesheet">
		<link href="../_/css/font-awesome.css" rel="stylesheet">
		<link href="../_/css/BoxComponant.css" rel="stylesheet">
		<link href="../_/css/site.css" rel="stylesheet">
		<link href="../_/css/bootstrap-datepicker.css" rel="stylesheet">
		<link href="../_/css/wickedpicker.min.css" rel="stylesheet">
		<link href="../_/css/datepicker.css" rel="stylesheet">
		<link href="../_/css/fullcalendar.css" rel="stylesheet"><!----calender--->
		<link href="../_/css/fullcalendar.print.css" rel="stylesheet"><!----calender--->
		<link href="../_/css/material-charts.css" rel="stylesheet">
		<link href="../_/css/style.css" rel="stylesheet">