<script src="../_/js/jquery-2.1.1.min.js"></script>
<script src="../_/js/jquery-1.10.1.min.js"></script>
<script src="../_/js/jquery-1.11.3.min.js"></script><!----calender--->
<script src="../_/js/jquery.min.js"></script>
<script src="../_/js/jquery-ui.js"></script>
<script src="../_/js/jquery-ui-1.10.2.custom.min.js"></script><!----calender--->
<script src="../_/js/bootstrap.min.js"></script> 
<script src="../_/js/material-charts.js"></script> 
<script src="../_/js/animatedModal.min.js"></script> 
<script src="../_/js/fullcalendar.min.js"></script>	<!----calender--->
<script src="../_/js/site.js"></script> 
<script src="../_/js/Atrag.js"></script>
